version: '3.8'

services:
  db:
    image: postgres:16beta2
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tgbot
    ports:
      - '5432:5432'
    volumes:
      - db_tgbot_psql:/var/lib/postgresql/data

volumes:
  db_tgbot_psql:
    driver: local


